# Generated by Django 5.2.8 on 2025-11-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('used_for', models.TextField()),
                ('image', models.ImageField(upload_to='plant_images/')),
                ('category', models.CharField(choices=[('tree', 'Tree'), ('shrub', 'Shrub'), ('flower', 'Flower'), ('herb', 'Herb'), ('cactus', 'Cactus'), ('other', 'Other')], default='other', max_length=20)),
                ('is_edible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
